### ISSUE TITLE
Increase max-age when set name.

### ISSUE THREAD

**Issue by H4ad** [boringdesigners/boring-avatars-service#5]
**Is your feature request related to a problem? Please describe.**

I've seen you set `cache-control: s-max-age=1`:
https://github.com/hihayk/boring-avatars-service/blob/1cf355b12ec0aa3b2be284641da32ec1105b55ab/api/index.js#L38

But it only lasts for a second, so I experienced a lot of cache misses.

From what I can see, the boring avatar is the same if we specify `name`.
So the `cache-control` for when the user sends `name` should be high.

**Describe the solution you'd like**

Increase the cache control to something like a day or a week.
In express, is something like:

```js
// only cache if name is passed.
if (req.query.name || req.params.name) {
  // ref: https://vercel.com/docs/concepts/functions/serverless-functions/edge-caching#recommended-cache-control
  res.setHeader('Cache-Control', 'max-age=0, s-maxage=86400');
} else {
  res.setHeader('Cache-control', 'max-age=0, s-max-age=1');
}
```

**Comment by vieron** [comment]
Thanks! We just merged and deployed this change
