### ISSUE TITLE
[Feature]: Make this a standalone Library

### ISSUE THREAD

**Issue by johannesschobel** [boringdesigners/boring-avatars-service#8]
Dear BoringDesigners @josepmartins ,

thanks for this awesome service, i really like it. I would like to use this service in my standalone application - however, i would like to create / generate the avatars on my own (i.e., without making an HTTP GET call to your service).

Would it be possible to have a dedicated npm library to generate the avatars myself? i.e., something like this:

```ts
const svg = generateAvatar('marble', { ... });
const avatar = svg.toString();
```

All the best and thanks for your help,
Johannes

**Comment by josepmartins** [comment]
I see, we don't have any plans to work on a library that extends to other languages anytime soon.

**Comment by johannesschobel** [comment]
thanks for your answer. that is very unfortunate.
All the best,
Johannes
